name: repo-sync

on:
  schedule:
    - cron: '0 12 * * 1'

  workflow_dispatch:

jobs:
  repo-sync:
    if: ${{ github.repository != 'yaoysyao/Auto_CheckIn' }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: repo-sync
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "https://github.com/yaoysyao/Auto_CheckIn.git"
          source_branch: "main"
          destination_branch: "main"
          sync_tags: "true"
          github_token: ${{ secrets.REPOSYNC_TOKEN }}